server:
  port: 8082
spring:
  application:
    name: CUSTOMER-SERVICE
  datasource:
    name:
    url:
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
